#!/bin/sh

. /scripts/functions.sh

export PGPASSWORD=$DB_ENV_POSTGRES_PASSWORD
export PGDATABASE=$DB_ENV_POSTGRES_DB
export PGUSER=$DB_ENV_POSTGRES_USER
export PGHOST=db

info "checking if database has been initialized"
if psql -w -c 'SELECT 1 FROM Tickets;' > /dev/null 2>&1; then
	info "database exists"
	exit 0
else
	info "database does not exist"
	exit 1
fi
