#!/bin/sh

. /scripts/functions.sh

: ${DB_CONNECT_RETRIES:=20}

export PGPASSWORD=$DB_ENV_POSTGRES_PASSWORD
export PGDATABASE=$DB_ENV_POSTGRES_DB
export PGUSER=$DB_ENV_POSTGRES_USER
export PGHOST=db

for i in $(seq 1 1 $DB_CONNECT_RETRIES); do
	info "trying to connect to postgres ($i)"

	if psql -w -c 'SELECT version();'; then
		info "postgres is ready"
		exit 0
	else
		sleep 5
	fi
done

fatal "failed to connect to postgres"
