#!/bin/sh

. /scripts/functions.sh

if [ -n "$DB_ENV_POSTGRES_USER" ]; then
	DB_TYPE=pg
elif [ -n "$DB_ENV_MYSQL_USER" ]; then
	DB_TYPE=mysql
else
	DB_TYPE=sqlite
fi

info "detected database type $DB_TYPE"
ln -s /scripts/dbdrivers/$DB_TYPE /scripts/db
/scripts/db/config

