#!/bin/sh

. /scripts/functions.sh

FETCHMAILRC=/home/rt4/fetchmailrc

info 'generating fetchmail configuration'

: ${FETCHMAIL_PROTO:=pop3}

if echo "${FETCHMAIL_TLS:-on}" | is_true; then
	info 'enabling ssl for fetchmail'
	TLS_ENABLED=1
fi

if [ -z "$FETCHMAIL_PORT" ]; then
	if [ "$TLS_ENABLED" = 1 ]; then
		case "$FETCHMAIL_PROTO" in
			imap)	FETCHMAIL_PORT=993
				;;
			pop*)	FETCHMAIL_PORT=995
				FETCHMAIL_PROTO=pop3
				;;
			*)	fatal "unknown email protocol: $FETCHMAIL_PROTO"
				;;
		esac
	fi
fi

(
cat <<EOF
poll $FETCHMAIL_HOST proto $FETCHMAIL_PROTO ${FETCHMAIL_PORT:+port $FETCHMAIL_PORT}
username $FETCHMAIL_USER password $FETCHMAIL_PASS
  mda "/usr/bin/rt-mailgate --url http://rt/ --queue General --action correspond"
EOF

if [ "$TLS_ENABLED" = 1 ]; then
	echo "  options ssl"
fi
) > $FETCHMAILRC

chown rt4:rt4 $FETCHMAILRC
chmod 600 $FETCHMAILRC
