#!/bin/sh

cat <<EOF
Set(\$rtname, '$RT_NAME');
Set(\$Organization, '$RT_DOMAIN');
Set(\$WebDomain, '${RT_WEBDOMAIN}');
Set(\$WebPath, '$RT_WEBPATH');
Set(\$CorrespondAddress, '$RT_CORRESPONDADDRESS');
Set(\$CommentAddress, '$RT_COMMENTADDRESS');
Set(\$SendmailPath, '/usr/bin/msmtp');
Set(@ReferrerWhitelist, qw/${RT_WEBDOMAIN}:80 ${RT_WEBDOMAIN}:443/);
EOF

