#!/bin/sh

echo "[i] loading sitedata"

if ! cd /etc/rt4/sitedata; then
	echo "[i] nothing to load" >&2
	exit
fi

for datafile in *; do
	[ -f "$datafile" ] || continue

	echo "[i] loading data from $datafile"
	rt-setup-database --action insert \
		--datafile "$datafile" \
		--skip-create
done

