#!/bin/sh

. /scripts/functions.sh

info "loading sitedata"

if ! cd /etc/rt4/sitedata; then
	info 'nothing to load'
	exit
fi

for datafile in *; do
	[ -f "$datafile" ] || continue

	info "loading data from $datafile"
	rt-setup-database --action insert \
		--datafile "$datafile" \
		--skip-create
done

