#!/bin/sh

. /scripts/functions.sh

info "checking if database has been initialized"
if mysql -B --connect-timeout=1 -h db -u $DB_ENV_MYSQL_USER \
		-p$DB_ENV_MYSQL_PASSWORD \
		-e "SELECT 1 FROM Tickets;" $DB_ENV_MYSQL_DATABASE > /dev/null 2>&1; then
	info "database exists"
	exit 0
else
	info "database does not exist"
	exit 1
fi
