#!/bin/sh

. /scripts/functions.sh

: ${DB_CONNECT_RETRIES:=20}

for i in $(seq 1 1 $DB_CONNECT_RETRIES); do
	info "trying to connect to mysql ($i)"

	if mysql -B --connect-timeout=1 -h db -u $DB_ENV_MYSQL_USER \
			-p$DB_ENV_MYSQL_PASSWORD \
			-e "SELECT version();" $DB_ENV_MYSQL_DATABASE; then
		info "mysql is ready"
		exit 0
	else
		sleep 5
	fi
done

fatal "failed to connect to mysql"
